language: php
php:
    - 7.3
    - 7.4

sudo: false

before_script:
    # Update & configure composer.
    - composer self-update --2
    - composer --version

    # Get the CodeClimate test reporter.
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
    - composer install -n

script:
    - vendor/bin/grumphp run

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
